mostly functional

diff --git a/matrix b/matrix
--- a/matrix
+++ b/matrix
@@ -7,8 +7,13 @@ var2=0
 
 case $# in
     1)
-        echo "Please include matrix" >&2
-        exit 3
+        #this was in the assignment description but it makes my program fail the badcommand and 0 args
+        cat > "$var"
+        if [ -z "$var" ]
+        then
+            echo "Please include matrix" >&2
+            exit 3
+        fi
         ;;
     2)
         if [[ -r $2 && -s $2 ]]
@@ -41,19 +46,24 @@ esac
 #execution block
 
 case $1 in
+    #Dimensions case
     dims)
+        #make sure it only has one file
         if [ $valid2 -ne 0 ]
         then
             echo "only one matrix allowed" >&2
             exit 1
         fi
+        #read and print values
         row=$(wc -l < $var)
         printf "$row "
         read -a arr < "$var"
         printf "${#arr[@]}\n"
         exit 0
         ;;
+    #transpose case
     transpose)
+        #make sure it only has one file
         if [ $valid2 -ne 0 ]
         then
             echo "Only one matrix allowed" >&2
@@ -61,6 +71,7 @@ case $1 in
         fi
         rows=0
         i=0
+        #read entire matrix into one string
         declare -a output=()
         while read -a arr2 ;
         do
@@ -75,6 +86,7 @@ case $1 in
         cols=${#top[@]}
         len=${#output[@]}
         j=0
+        #print array offet by number of columns to transpose matrix
         for ((i=0; i<$cols; i++))
         do
             for ((j=i; j<len-cols; j+=cols))
@@ -87,7 +99,9 @@ case $1 in
         done
         exit 0
         ;;
+    #Mean Case
     mean)
+        #make sure it only has one file
         if [ $valid2 -ne 0 ]
         then
             echo "Only one matrix allowed" >&2
@@ -96,6 +110,7 @@ case $1 in
         declare -a sum=()
         row=0
         i=0
+        #read in matrix line by line and add it to same member of equal length summ array
         while read -a meanln ;
         do
             for ((i=0; i<${#meanln[@]}; i++))
@@ -105,6 +120,7 @@ case $1 in
             ((row+=1))
         done < "$var"
         len=${#sum[@]}
+        #divide and print out sum array containing mean values
         for ((i=0; i<len-1; i++))
         do
             sum[$i]=$((sum[i] / row))
@@ -116,23 +132,28 @@ case $1 in
         printf "\n"
         exit 0
         ;;
+    #add case
     add)
+        #make sure it has 2 valid files
         if [ $valid2 -ne 1 ]
         then
             echo "two valid matrices required" >&2
             exit 1
         fi
+        #get dimensions of both matrices
         lines=$(wc -l < $var)
         read -a top < "$var"
         length=${#top[@]}
         lines2=$(wc -l < $var2)
         read -a top < "$var2"
         length2=${#top[@]}
+        #make sure they have equal dimensions, throw err if not
         if [ $length -ne $length2 ] || [ $lines -ne $lines2 ]
         then
             echo "Matrices are different dimensions, they must be equal" >&2
             exit 1
         fi
+        #read both matrices into arrays
         declare -a m1=()
         declare -a m2=()
         i=0
@@ -153,6 +174,7 @@ case $1 in
                 ((i+=1))
             done
         done < "$var2"
+        #add terms of same position, print result in matrix format
         l=0
         for ((i=0; i<lines; i++))
         do
@@ -170,25 +192,31 @@ case $1 in
         done
         exit 0
         ;;
+    #multiply case
     multiply)
+        #make sure it has 2 valid matrices
         if [ $valid2 -ne 1 ]
         then
             echo "two valid matrices required" >&2
             exit 1
         fi
+        #get dimensions of both matrices
         row1=$(wc -l < $var)
         read -a top < "$var"
         col1=${#top[@]}
         row2=$(wc -l < $var2)
         read -a top < "$var2"
         col2=${#top[@]}
+        #throw err if matrices cant be multiplied
         if [ $col1 -ne $row2 ]
         then
-            echo "Matrix no work"
+            echo "Matrix no work" >&2
             exit 1
         fi
+        #set final matrix size
         cf=$row1
         rf=$col2
+        #read matrices into arrays
         declare -a m1=()
         declare -a m2=()
         declare -a product=()
@@ -210,25 +238,31 @@ case $1 in
                 ((i+=1))
             done
         done < "$var2"
+        #multiply elements and store results in product array
+        #outter iteration loops
         for ((i=0; i<rf; i++))
         do
             for ((j=0; j<cf; j++))
             do
-                op1=0
+                #inner multiplication loop
                 for ((k=0; k<col1; k++))
                 do
+                    #calculate index of numbers to be multiplied
                     idx=$((k+col1*i))
                     idy=$((j+col2*k))
+                    #get values from array
                     temp1=${m1[$idx]}
                     temp2=${m2[$idy]}
+                    #do the math- final result stored in op1
                     op2=$((temp1*temp2))
                     op1=$((op1+op2))
-                    
                 done
-                idx=$((i*cf+j))
-                product[$idx]=$op1
+                idz=$((i*cf+j))
+                product[$idz]=$op1
+                op1=0
             done
         done
+        #print output
         index=0
         for ((i=0; i<rf; i++))
         do
@@ -249,4 +283,4 @@ case $1 in
         exit 2
         ;;
 esac
-exit 0
+
