Fixed directory

diff --git a/prog1/matrix b/prog1/matrix
--- a/prog1/matrix
+++ b/prog1/matrix
@@ -1,34 +1,38 @@
 #!/bin/bash
-echo $0
 valid2=0
 var=0
 var2=0
+#Argument verification block
+
 case $# in
-    0)
-        echo "Please enter matrix [operation] [m1] [m2]" >&2
-        exit 2;;
     1)
-        echo "Please include matrix" >&2
+        #this was in the assignment description but it makes my program fail the badcommand and 0 args
         cat > "$var"
-        exit 2;;
+        if [ -z "$var" ]
+        then
+            echo "Please include matrix" >&2
+            exit 3
+        fi
+        ;;
     2)
+        #if file is readable and not empty, store filepath
         if [[ -r $2 && -s $2 ]]
         then
-            var="/nfs/stak/users/carlsosp/os1/prog1/$2"
-            echo "---- Result ----"
+            var="$( cd "$(dirname "${BASH_SOURCE[0]}")" && pwd )/$2"
         else
             echo "Enter valid matrix" >&2
             exit 1
-        fi;;
+        fi
+        ;;
     3)
+        #if files are readable and not empty, store filepaths
         if [[ -r $2 && -s $2 ]]
         then
             if [[ -r $3 && -s $3 ]]
             then
                 valid2=1
-                var="/nfs/stak/users/carlsosp/os1/prog1/$2"
-                var2="/nfs/stak/users/carlsosp/os1/prog1/$3"
-                echo "---- Result ----"
+                var="$( cd "$(dirname "${BASH_SOURCE[0]}")" && pwd )/$2"
+                var2="$( cd "$(dirname "${BASH_SOURCE[0]}")" && pwd )/$3"
             else
                 echo "Error reading second matrix" >&2
                 exit 1
@@ -36,23 +40,39 @@ case $# in
         else
             echo "Error reading first matrix" >&2
             exit 1
-        fi;;
-    \?)
+        fi
         ;;
 esac
+
+#execution block
+
 case $1 in
+    #Dimensions case
     dims)
-        printf "Rows: "
-        echo | wc -l < "$var"
-        printf "Columns: "
+        #make sure it only has one file
+        if [ $valid2 -ne 0 ]
+        then
+            echo "only one matrix allowed" >&2
+            exit 1
+        fi
+        #read and print values
+        row=$(wc -l < $var)
+        printf "$row "
         read -a arr < "$var"
-        echo "${#arr[@]}"
-        exit 0;;
+        printf "${#arr[@]}\n"
+        exit 0
+        ;;
+    #transpose case
     transpose)
-        #cut -f1 $var > read -a arr3
-        #echo ${arr3[@]}
+        #make sure it only has one file
+        if [ $valid2 -ne 0 ]
+        then
+            echo "Only one matrix allowed" >&2
+            exit 1
+        fi
         rows=0
         i=0
+        #read entire matrix into one string
         declare -a output=()
         while read -a arr2 ;
         do
@@ -65,54 +85,209 @@ case $1 in
         done < "$var"
         read -a top < "$var"
         cols=${#top[@]}
-        rows=0
+        len=${#output[@]}
+        j=0
+        #print array offet by number of columns to transpose matrix
         for ((i=0; i<$cols; i++))
         do
-            for ((j=i; j<${#output[@]}; j+=cols))
+            for ((j=i; j<len-cols; j+=cols))
             do
                 printf "%s"${output[j]}
                 printf "	"
             done
+            printf "%s"${output[j]}
             printf "\n"
         done
+        exit 0
         ;;
+    #Mean Case
     mean)
-        echo "mean option"
+        #make sure it only has one file
+        if [ $valid2 -ne 0 ]
+        then
+            echo "Only one matrix allowed" >&2
+            exit 1
+        fi
+        declare -a sum=()
+        row=0
+        i=0
+        #read in matrix line by line and add it to same member of equal length summ array
+        while read -a meanln ;
+        do
+            for ((i=0; i<${#meanln[@]}; i++))
+            do
+                ((sum[i] += meanln[i]))
+            done
+            ((row+=1))
+        done < "$var"
+        len=${#sum[@]}
+        #divide and print out sum array containing mean values
+        for ((i=0; i<len-1; i++))
+        do
+            temp=$(((sum[i]>0)*2-1))
+            temp=$(((row/2)*temp))
+            temp=$((sum[i]+temp))
+            sum[$i]=$((temp/row))
+            printf "%s"${sum[$i]}
+            printf "	"
+        done
+        temp=$(((sum[i]>0)*2-1))
+        temp=$(((row/2)*temp))
+        temp=$((sum[i]+temp))
+        sum[$i]=$((temp/row))
+        printf "%s"${sum[$i]}
+        printf "\n"
+        exit 0
         ;;
+    #add case
     add)
+        #make sure it has 2 valid files
         if [ $valid2 -ne 1 ]
         then
             echo "two valid matrices required" >&2
             exit 1
         fi
-        echo "add option"
+        #get dimensions of both matrices
+        lines=$(wc -l < $var)
+        read -a top < "$var"
+        length=${#top[@]}
+        lines2=$(wc -l < $var2)
+        read -a top < "$var2"
+        length2=${#top[@]}
+        #make sure they have equal dimensions, throw err if not
+        if [ $length -ne $length2 ] || [ $lines -ne $lines2 ]
+        then
+            echo "Matrices are different dimensions, they must be equal" >&2
+            exit 1
+        fi
+        #read both matrices into arrays
+        declare -a m1=()
+        declare -a m2=()
+        i=0
+        while read -a arr2 ;
+        do
+            for ((j=0; j<$length; j++))
+            do
+                m1[$i]=${arr2[$j]}
+                ((i+=1))
+            done
+        done < "$var"
+        i=0
+        while read -a arr ;
+        do
+            for ((j=0; j<$length; j++))
+            do
+                m2[$i]=${arr[$j]}
+                ((i+=1))
+            done
+        done < "$var2"
+        #add terms of same position, print result in matrix format
+        l=0
+        for ((i=0; i<lines; i++))
+        do
+            for ((j=0; j<length-1; j++))
+            do
+                temp=$((m1[l] + m2[l]))
+                printf "%s"$temp
+                printf "	"
+                ((l+=1))
+            done
+            temp=$((m1[l] + m2[l]))
+            ((l+=1))
+            printf "%s"$temp
+            printf "\n"
+        done
+        exit 0
         ;;
+    #multiply case
     multiply)
+        #make sure it has 2 valid matrices
         if [ $valid2 -ne 1 ]
         then
             echo "two valid matrices required" >&2
             exit 1
         fi
-        echo "mult option"
+        #get dimensions of both matrices
+        row1=$(wc -l < $var)
+        read -a top < "$var"
+        col1=${#top[@]}
+        row2=$(wc -l < $var2)
+        read -a top < "$var2"
+        col2=${#top[@]}
+        #throw err if matrices cant be multiplied
+        if [ $col1 -ne $row2 ]
+        then
+            echo "Matrix no work" >&2
+            exit 1
+        fi
+        #set final matrix size
+        cf=$col2
+        rf=$row1
+        #read matrices into arrays
+        declare -a m1=()
+        declare -a m2=()
+        declare -a product=()
+        i=0
+        while read -a arr2 ;
+        do
+            for ((j=0; j<$col1; j++))
+            do
+                m1[$i]=${arr2[$j]}
+                ((i+=1))
+            done
+        done < "$var"
+        i=0
+        while read -a arr ;
+        do
+            for ((j=0; j<$col2; j++))
+            do
+                m2[$i]=${arr[$j]}
+                ((i+=1))
+            done
+        done < "$var2"
+        #multiply elements and store results in product array
+        #outter iteration loops
+        for ((i=0; i<rf; i++))
+        do
+            for ((j=0; j<cf; j++))
+            do
+                #inner multiplication loop
+                for ((k=0; k<col1; k++))
+                do
+                    #calculate index of numbers to be multiplied
+                    idx=$((k+col1*i))
+                    idy=$((j+col2*k))
+                    #get values from array
+                    temp1=${m1[$idx]}
+                    temp2=${m2[$idy]}
+                    #do the math- final result stored in op1
+                    op2=$((temp1*temp2))
+                    op1=$((op1+op2))
+                done
+                idz=$((i*cf+j))
+                product[$idz]=$op1
+                op1=0
+            done
+        done
+        #print output
+        index=0
+        for ((i=0; i<rf; i++))
+        do
+            for ((j=0; j<cf-1; j++))
+            do
+                printf "%s"${product[$index]}
+                printf "	"
+                ((index+=1))
+            done
+            printf "%s"${product[$index]}
+            printf "\n"
+            ((index+=1))
+        done
+        exit 0
         ;;
     \?) 
         echo "enter: dims, transpose, mean, add, or multiply" >&2
         exit 2
+        ;;
 esac
-
-#transpose function
-#reflects matrix along main diagonal
-#function trans()
-
-##mean function
-#creates 1xn matrix with average of each column
-#function mean()
-
-#add function
-#adds matrices and throws err if dims!=
-#function add()
-
-#mulitply function
-#multiplies 2 matrices
-#function mult()
 
